name: 'Claude Code Security Scanner'
description: 'AI-powered comprehensive security scanner using Claude to analyze entire application codebases for security vulnerabilities'
author: 'Anthropic'

inputs:
  upload-sarif:
    description: 'Whether to upload SARIF results to GitHub Code Scanning'
    required: false
    default: 'true'
  
  upload-results:
    description: 'Whether to upload results as artifacts'
    required: false
    default: 'true'
  
  exclude-directories:
    description: 'Comma-separated list of directories to exclude from scanning'
    required: false
    default: ''

  claudecode-timeout:
    description: 'Timeout for ClaudeCode analysis in minutes'
    required: false
    default: '20'
  
  claude-api-key:
    description: 'Anthropic Claude API key for security analysis'
    required: true
    default: ''

  claude-model:
    description: 'Claude model to use for security analysis (e.g., claude-sonnet-4-5-20250929)'
    required: false
    default: 'claude-sonnet-4-5'

  branch:
    description: 'Branch to scan (defaults to repository default branch)'
    required: false
    default: ''

  false-positive-filtering-instructions:
    description: 'Path to custom false positive filtering instructions text file'
    required: false
    default: ''

  custom-security-scan-instructions:
    description: 'Path to custom security scan instructions text file to append to audit prompt'
    required: false
    default: ''

  review-existing-alerts:
    description: 'Whether to review and persist existing open Code Scanning alerts'
    required: false
    default: 'true'

outputs:
  findings-count:
    description: 'Number of security findings'
    value: ${{ steps.claudecode-scan.outputs.findings_count }}
  
  results-file:
    description: 'Path to the results JSON file'
    value: ${{ steps.claudecode-scan.outputs.results_file }}

runs:
  using: 'composite'
  steps:
    - name: Install GitHub CLI
      shell: bash
      run: |
        echo "::group::Install gh CLI"
        # Install GitHub CLI for PR operations
        sudo apt-get update && sudo apt-get install -y gh
        echo "::endgroup::"
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Determine scan branch
      id: scan-branch
      shell: bash
      env:
        INPUT_BRANCH: ${{ inputs.branch }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch || 'main' }}
      run: |
        if [ -n "$INPUT_BRANCH" ]; then
          echo "scan_branch=$INPUT_BRANCH" >> $GITHUB_OUTPUT
          echo "Scanning branch: $INPUT_BRANCH (user specified)"
        else
          echo "scan_branch=$DEFAULT_BRANCH" >> $GITHUB_OUTPUT
          echo "Scanning branch: $DEFAULT_BRANCH (repository default)"
        fi
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: |
        echo "::group::Install Deps"
        pip install -r "$ACTION_PATH/claudecode/requirements.txt"
        npm install -g @anthropic-ai/claude-code
        sudo apt-get update && sudo apt-get install -y jq
        echo "::endgroup::"
    
    - name: Checkout target branch
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.scan-branch.outputs.scan_branch }}
        fetch-depth: 0
    
    - name: Run Claude Security Scanner
      id: claudecode-scan
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ANTHROPIC_API_KEY: ${{ inputs.claude-api-key }}
        ENABLE_CLAUDE_FILTERING: 'true' 
        EXCLUDE_DIRECTORIES: ${{ inputs.exclude-directories }}
        FALSE_POSITIVE_FILTERING_INSTRUCTIONS: ${{ inputs.false-positive-filtering-instructions }}
        CUSTOM_SECURITY_SCAN_INSTRUCTIONS: ${{ inputs.custom-security-scan-instructions }}
        CLAUDE_MODEL: ${{ inputs.claude-model }}
        CLAUDECODE_TIMEOUT: ${{ inputs.claudecode-timeout }}
        ACTION_PATH: ${{ github.action_path }}
        SCAN_BRANCH: ${{ steps.scan-branch.outputs.scan_branch }}
        UPLOAD_RESULTS_TO_REPO: ${{ inputs.upload-sarif }}
        SARIF_OUTPUT_PATH: claude-security-findings.sarif
        REVIEW_EXISTING_ALERTS: ${{ inputs.review-existing-alerts }}
      run: |
        echo "Running Claude AI comprehensive security analysis..."
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Branch: $SCAN_BRANCH"
        echo "----------------------------------------"
        
        # Initialize outputs
        echo "findings_count=0" >> $GITHUB_OUTPUT
        echo "results_file=claudecode/claudecode-results.json" >> $GITHUB_OUTPUT
        
        # Validate API key is provided
        if [ -z "$ANTHROPIC_API_KEY" ]; then
          echo "::error::ANTHROPIC_API_KEY is not set. Please provide the claude-api-key input to the action."
          echo "Example usage:"
          echo "  - uses: anthropics/claude-code-security-reviewer@main"
          echo "    with:"
          echo "      claude-api-key: \$\{{ secrets.ANTHROPIC_API_KEY }}"
          exit 1
        fi
                
        # Set timeout
        export CLAUDE_TIMEOUT="$CLAUDECODE_TIMEOUT"
        
        # Run ClaudeCode audit with verbose debugging
        export REPO_PATH=$(pwd)
        cd "$ACTION_PATH"
        
        # Enable verbose debugging
        echo "::group::ClaudeCode Environment"
        echo "Current directory: $(pwd)"
        echo "Python version: $(python --version)"
        echo "Claude CLI version: $(claude --version 2>&1 || echo 'Claude CLI not found')"
        echo "ANTHROPIC_API_KEY set: $(if [ -n "$ANTHROPIC_API_KEY" ]; then echo 'Yes'; else echo 'No'; fi)"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        echo "SCAN_BRANCH: $SCAN_BRANCH"
        echo "Python path: $PYTHONPATH"
        echo "Files in claudecode directory:"
        ls -la claudecode/
        echo "::endgroup::"
        
        echo "::group::ClaudeCode Execution"
        # Add current directory to Python path so it can find the claudecode module
        export PYTHONPATH="${PYTHONPATH:+$PYTHONPATH:}$(pwd)"
        echo "Updated PYTHONPATH: $PYTHONPATH"
        
        # Run from the action root directory so Python can find the claudecode module
        python -u claudecode/github_action_audit.py > claudecode/claudecode-results.json 2>claudecode/claudecode-error.log || CLAUDECODE_EXIT_CODE=$?
        
        if [ -n "$CLAUDECODE_EXIT_CODE" ]; then
          echo "::warning::ClaudeCode exited with code $CLAUDECODE_EXIT_CODE"
        else
          echo "ClaudeCode scan completed successfully"
        fi
        
        # Parse ClaudeCode results and count findings regardless of exit code
        if [ -f claudecode/claudecode-results.json ]; then
          FILE_SIZE=$(wc -c < claudecode/claudecode-results.json)
          echo "ClaudeCode results file size: $FILE_SIZE bytes"
          
          # Check if file is empty or too small
          if [ "$FILE_SIZE" -lt 2 ]; then
            echo "::warning::ClaudeCode results file is empty or invalid (size: $FILE_SIZE bytes)"
            echo "::warning::ClaudeCode may have failed silently. Check claudecode-error.log"
            if [ -f claudecode/claudecode-error.log ]; then
              echo "Error log contents:"
              cat claudecode/claudecode-error.log
            fi
            echo "findings_count=0" >> $GITHUB_OUTPUT
          else
            echo "ClaudeCode results preview:"
            head -n 300 claudecode/claudecode-results.json || echo "Unable to preview results"
                        
            # Check if the result is an error
            if jq -e '.error' claudecode/claudecode-results.json > /dev/null 2>&1; then
              ERROR_MSG=$(jq -r '.error' claudecode/claudecode-results.json)
              echo "::warning::ClaudeCode error: $ERROR_MSG"
              echo "findings_count=0" >> $GITHUB_OUTPUT
            else
              # Use -r to get raw output and handle potential null/missing findings array
              CLAUDECODE_FINDINGS_COUNT=$(jq -r '.findings | if . == null then 0 else length end' claudecode/claudecode-results.json 2>/dev/null || echo "0")
              echo "::debug::Extracted ClaudeCode findings count: $CLAUDECODE_FINDINGS_COUNT"
              echo "findings_count=$CLAUDECODE_FINDINGS_COUNT" >> $GITHUB_OUTPUT
              echo "ClaudeCode found $CLAUDECODE_FINDINGS_COUNT security issues"
              
              # Also create findings.json for PR comment script
              jq '.findings // []' claudecode/claudecode-results.json > findings.json || echo '[]' > findings.json
            fi
          fi
        else
          echo "::warning::ClaudeCode results file not found"
          if [ -f claudecode/claudecode-error.log ]; then
            echo "Error log contents:"
            cat claudecode/claudecode-error.log
          fi
          echo "findings_count=0" >> $GITHUB_OUTPUT
        fi
        
        # Always copy files to workspace root regardless of the outcome
        # This ensures artifact upload and PR commenting can find them
        if [ -f findings.json ]; then
          cp findings.json ${{ github.workspace }}/findings.json || true
        fi
        if [ -f claudecode/claudecode-results.json ]; then
          cp claudecode/claudecode-results.json ${{ github.workspace }}/claudecode-results.json || true
        fi
        if [ -f claudecode/claudecode-error.log ]; then
          cp claudecode/claudecode-error.log ${{ github.workspace }}/claudecode-error.log || true
        fi
        
        echo "::endgroup::"
    
    
    - name: Upload scan results
      if: always() && inputs.upload-results == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: security-review-results
        path: |
          findings.json
          claudecode-results.json
          claudecode-error.log
        retention-days: 7
        if-no-files-found: ignore
    
    - name: Upload SARIF to GitHub Code Scanning
      if: inputs.upload-sarif == 'true' && always() && hashFiles('claude-security-findings.sarif') != ''
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: claude-security-findings.sarif
        category: Claude-Security-Scanner
        wait-for-processing: false

branding:
  icon: 'shield'
  color: 'red'
